name: bili2text-cli
channels:
  - defaults
  - conda-forge
dependencies:
  # Python 核心
  - python=3.11
  - pip
  
  # 系统依赖
  - ffmpeg
  
  # pip 安装的包
  - pip:
    # 核心功能包
    - bilibili-api-python
    - bilix==0.18.5
    
    # 网络和异步
    - httpx==0.26.0
    - aiofiles==23.2.1
    
    # 数据处理
    - beautifulsoup4==4.12.2
    - click==8.1.7
    
    # 进度显示
    - tqdm==4.66.1
    - rich==13.7.0